In [42]:
import numpy as np
edges_all = np.loadtxt('data/bonanza_buyer_item_seller_id_R_2.txt', delimiter='::')
edges_all = edges_all.astype(int)
print(edges_all)

[[         0          0          0 1548565200]
 [         0          0          1 1548565200]
 [         1          0          2 1539144000]
 ...
 [      4843       3116       1492 1537588800]
 [      8920       3117         35 1531454400]
 [      8921       3118        235 1552194000]]


In [43]:
buyer_item = edges_all[:, 0:2]
item_seller = edges_all[:, 1:3]

In [53]:
indices = np.arange(edges_all.shape[0])
np.random.shuffle(indices)

nums = edges_all.shape[0]
num_val = int(nums * 0.15)
num_test = int(nums * 0.15)
num_train = nums - num_val - num_test

train_indices = indices[:num_train]
val_indices = indices[num_train:num_train+num_val]
test_indices = indices[num_train+num_val:]


train_set = {}
val_set = {}
test_set = {}
buyer_item_set = {}
buyer_train = []
buyer_val = []
buyer_test = []
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1
    if i in train_indices:
        train_set[pair] = 1
        buyer_train.append(buyer_item[i, 0].item())
    elif i in val_indices:
        val_set[pair] = 1
        buyer_val.append(buyer_item[i, 0].item())
    elif i in test_indices:
        test_set[pair] = 1
        buyer_test.append(buyer_item[i, 0].item())
    else:
        print("Error")

buyer_item_outputs = []
train_outputs = []
val_outputs = []
test_outputs = []
for idx, (pair, count) in enumerate(buyer_item_set.items()):
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)
    if pair in train_set.keys():
        train_outputs.append(idx)
    if pair in val_set.keys():
        val_outputs.append(idx)
    if pair in test_set.keys():
        test_outputs.append(idx)
train_outputs = np.array(train_outputs, dtype=int)
val_outputs = np.array(val_outputs, dtype=int)
test_outputs = np.array(test_outputs, dtype=int)
print(train_outputs.shape)
print(val_outputs.shape)
print(test_outputs.shape)
print(buyer_test)

(19135,)
(5139,)
(5209,)
[4, 6, 1, 8, 15, 19, 20, 28, 30, 33, 35, 35, 36, 5, 5, 40, 44, 44, 45, 47, 47, 47, 46, 5, 55, 5, 5, 62, 47, 70, 70, 5, 5, 79, 86, 87, 89, 92, 5, 106, 107, 114, 117, 119, 124, 9, 9, 8, 130, 141, 113, 113, 113, 161, 167, 13, 175, 6, 181, 182, 188, 194, 195, 196, 198, 199, 207, 207, 210, 211, 215, 216, 217, 217, 234, 255, 257, 258, 259, 260, 260, 268, 276, 279, 281, 294, 296, 298, 298, 306, 306, 309, 311, 314, 320, 323, 325, 331, 336, 338, 338, 343, 346, 348, 335, 356, 367, 368, 290, 376, 381, 384, 388, 252, 60, 29, 391, 394, 396, 399, 403, 414, 412, 375, 422, 423, 390, 426, 424, 375, 405, 429, 403, 405, 434, 419, 436, 437, 425, 356, 465, 467, 458, 472, 458, 306, 302, 477, 477, 477, 477, 390, 392, 483, 392, 52, 491, 418, 492, 493, 494, 495, 256, 412, 503, 507, 507, 511, 30, 468, 514, 294, 384, 535, 535, 536, 543, 547, 544, 346, 163, 22, 434, 276, 545, 297, 446, 563, 565, 562, 307, 254, 246, 250, 590, 454, 378, 378, 597, 378, 378, 598, 352, 594, 375, 378, 403, 608,

In [54]:
print(train_outputs)
with open('data/split/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)
np.savetxt('data/split/buyer_item_train.txt', train_outputs, fmt='%i')
np.savetxt('data/split/buyer_item_val.txt', val_outputs, fmt='%i')
np.savetxt('data/split/buyer_item_test.txt', test_outputs, fmt='%i')

buyer_train = np.array(buyer_train)
buyer_val = np.array(buyer_val)
buyer_test = np.array(buyer_test)
buyer_train.sort()
buyer_val.sort()
buyer_test.sort()
buyer_train = np.unique(buyer_train)
buyer_val = np.unique(buyer_val)
buyer_test = np.unique(buyer_test)
np.savetxt('data/split/buyer_train.txt', buyer_train, fmt='%i')
np.savetxt('data/split/buyer_val.txt', buyer_val, fmt='%i')
np.savetxt('data/split/buyer_test.txt', buyer_test, fmt='%i')

[    0     1     4 ... 24878 24880 24881]


In [55]:
train_set = {}
val_set = {}
test_set = {}
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1
    if i in train_indices:
        train_set[pair] = 1
    elif i in val_indices:
        val_set[pair] = 1
    elif i in test_indices:
        test_set[pair] = 1
    else:
        print("Error")

item_seller_outputs = []
train_outputs = []
val_outputs = []
test_outputs = []
for idx, (pair, count) in enumerate(item_seller_set.items()):
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    item_seller_outputs.append(line)
    if pair in train_set.keys():
        train_outputs.append(idx)
    if pair in val_set.keys():
        val_outputs.append(idx)
    if pair in test_set.keys():
        test_outputs.append(idx)
train_outputs = np.array(train_outputs, dtype=int)
val_outputs = np.array(val_outputs, dtype=int)
test_outputs = np.array(test_outputs, dtype=int)
print(train_outputs.shape)
print(val_outputs.shape)
print(test_outputs.shape)

(12814,)
(3763,)
(3673,)


In [56]:
print(train_outputs)
with open('data/split/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)
np.savetxt('data/split/item_seller_train.txt', train_outputs, fmt='%i')
np.savetxt('data/split/item_seller_val.txt', val_outputs, fmt='%i')
np.savetxt('data/split/item_seller_test.txt', test_outputs, fmt='%i')

[    0     1     2 ... 16629 16631 16632]


In [22]:
buyer_item_set = {}
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1

buyer_item_outputs = []
for pair, count in buyer_item_set.items():
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)

In [23]:
with open('data/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)

In [24]:
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1

item_seller_outputs = []
for pair, count in item_seller_set.items():
    item, seller = pair
    line = ' '.join([str(item), str(seller), str(count)]) + '\n'
    item_seller_outputs.append(line)

In [25]:
with open('data/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)