In [4]:
import numpy as np
edges_all = np.loadtxt('data/bonanza_buyer_item_seller_id_R_2.txt', delimiter='::')
edges_all = edges_all.astype(int)
print(edges_all)

[[         0          0          0 1548565200]
 [         0          0          1 1548565200]
 [         1          0          2 1539144000]
 ...
 [      4843       3116       1492 1537588800]
 [      8920       3117         35 1531454400]
 [      8921       3118        235 1552194000]]


In [5]:
buyer_item = edges_all[:, 0:2]
item_seller = edges_all[:, 1:3]

In [6]:
indices = np.arange(edges_all.shape[0])
np.random.shuffle(indices)

# change the ratio of data split
nums = edges_all.shape[0]
num_val = int(nums * 0)
num_test = int(nums * 0.5)
num_train = nums - num_val - num_test

train_indices = indices[:num_train]
val_indices = indices[num_train:num_train+num_val]
test_indices = indices[num_train+num_val:]


train_set = {}
val_set = {}
test_set = {}
buyer_item_set = {}
buyer_train = []
buyer_val = []
buyer_test = []
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1
    if i in train_indices:
        train_set[pair] = 1
        buyer_train.append(buyer_item[i, 0].item())
    elif i in val_indices:
        val_set[pair] = 1
        buyer_val.append(buyer_item[i, 0].item())
    elif i in test_indices:
        test_set[pair] = 1
        buyer_test.append(buyer_item[i, 0].item())
    else:
        print("Error")

buyer_item_outputs = []
train_outputs = []
val_outputs = []
test_outputs = []
for idx, (pair, count) in enumerate(buyer_item_set.items()):
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)
    if pair in train_set.keys():
        train_outputs.append(idx)
    if pair in val_set.keys():
        val_outputs.append(idx)
    if pair in test_set.keys():
        test_outputs.append(idx)
train_outputs = np.array(train_outputs, dtype=int)
val_outputs = np.array(val_outputs, dtype=int)
test_outputs = np.array(test_outputs, dtype=int)
print(train_outputs.shape)
print(val_outputs.shape)
print(test_outputs.shape)
print(buyer_test)

(14625,)
(0,)
(14585,)
[0, 3, 4, 6, 7, 8, 9, 11, 7, 13, 15, 16, 20, 0, 23, 25, 1, 27, 30, 34, 35, 37, 5, 5, 5, 39, 39, 39, 5, 5, 5, 42, 5, 5, 43, 44, 44, 44, 44, 44, 45, 47, 47, 47, 46, 48, 48, 50, 51, 52, 51, 51, 54, 5, 5, 55, 5, 55, 57, 55, 47, 55, 59, 5, 55, 47, 5, 61, 63, 65, 66, 69, 69, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 71, 71, 5, 5, 5, 5, 5, 5, 5, 5, 5, 42, 5, 5, 5, 5, 5, 74, 75, 77, 5, 79, 80, 80, 82, 5, 85, 86, 5, 89, 91, 92, 92, 5, 95, 99, 101, 100, 103, 105, 5, 106, 106, 108, 110, 113, 115, 116, 116, 116, 117, 117, 117, 117, 118, 120, 121, 5, 9, 9, 127, 128, 130, 134, 135, 136, 136, 138, 143, 144, 145, 144, 148, 149, 149, 150, 151, 113, 159, 159, 151, 162, 163, 165, 13, 13, 169, 170, 173, 175, 176, 178, 180, 180, 181, 182, 184, 186, 190, 188, 13, 13, 16, 16, 194, 195, 197, 16, 200, 201, 202, 205, 206, 207, 207, 207, 209, 209, 210, 210, 212, 212, 212, 212, 212, 212, 214, 208, 215, 217, 217, 218, 219, 221, 222, 222, 222, 218, 218, 224, 225, 225, 225, 222, 218, 227, 227, 2

In [7]:
print(train_outputs)
with open('data/split2/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)
np.savetxt('data/split2/buyer_item_train.txt', train_outputs, fmt='%i')
np.savetxt('data/split2/buyer_item_val.txt', val_outputs, fmt='%i')
np.savetxt('data/split2/buyer_item_test.txt', test_outputs, fmt='%i')

buyer_train = np.array(buyer_train)
buyer_val = np.array(buyer_val)
buyer_test = np.array(buyer_test)
buyer_train.sort()
buyer_val.sort()
buyer_test.sort()
buyer_train = np.unique(buyer_train)
buyer_val = np.unique(buyer_val)
buyer_test = np.unique(buyer_test)
np.savetxt('data/split2/buyer_train.txt', buyer_train, fmt='%i')
np.savetxt('data/split2/buyer_val.txt', buyer_val, fmt='%i')
np.savetxt('data/split2/buyer_test.txt', buyer_test, fmt='%i')

[    0     1     2 ... 24877 24880 24881]


In [8]:
train_set = {}
val_set = {}
test_set = {}
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1
    if i in train_indices:
        train_set[pair] = 1
    elif i in val_indices:
        val_set[pair] = 1
    elif i in test_indices:
        test_set[pair] = 1
    else:
        print("Error")

item_seller_outputs = []
train_outputs = []
val_outputs = []
test_outputs = []
for idx, (pair, count) in enumerate(item_seller_set.items()):
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    item_seller_outputs.append(line)
    if pair in train_set.keys():
        train_outputs.append(idx)
    if pair in val_set.keys():
        val_outputs.append(idx)
    if pair in test_set.keys():
        test_outputs.append(idx)
train_outputs = np.array(train_outputs, dtype=int)
val_outputs = np.array(val_outputs, dtype=int)
test_outputs = np.array(test_outputs, dtype=int)
print(train_outputs.shape)
print(val_outputs.shape)
print(test_outputs.shape)

(9829,)
(0,)
(9842,)


In [9]:
print(train_outputs)
with open('data/split2/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)
np.savetxt('data/split2/item_seller_train.txt', train_outputs, fmt='%i')
np.savetxt('data/split2/item_seller_val.txt', val_outputs, fmt='%i')
np.savetxt('data/split2/item_seller_test.txt', test_outputs, fmt='%i')

[    1     2     3 ... 16628 16631 16632]


In [10]:
buyer_item_set = {}
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1

buyer_item_outputs = []
for pair, count in buyer_item_set.items():
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)

In [23]:
with open('data/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)

In [24]:
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1

item_seller_outputs = []
for pair, count in item_seller_set.items():
    item, seller = pair
    line = ' '.join([str(item), str(seller), str(count)]) + '\n'
    item_seller_outputs.append(line)

In [25]:
with open('data/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)