In [11]:
import numpy as np
edges_all = np.loadtxt('data/bonanza_buyer_item_seller_id_R_2.txt', delimiter='::')
edges_all = edges_all.astype(int)
print(edges_all)

[[         0          0          0 1548565200]
 [         0          0          1 1548565200]
 [         1          0          2 1539144000]
 ...
 [      4843       3116       1492 1537588800]
 [      8920       3117         35 1531454400]
 [      8921       3118        235 1552194000]]


In [12]:
buyer_item = edges_all[:, 0:2]
item_seller = edges_all[:, 1:3]

In [22]:
buyer_item_set = {}
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1

buyer_item_outputs = []
for pair, count in buyer_item_set.items():
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)

In [23]:
with open('data/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)

In [24]:
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1

item_seller_outputs = []
for pair, count in item_seller_set.items():
    item, seller = pair
    line = ' '.join([str(item), str(seller), str(count)]) + '\n'
    item_seller_outputs.append(line)

In [25]:
with open('data/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)