In [18]:
import numpy as np
edges_all = np.loadtxt('data/bonanza_buyer_item_seller_id_R_2.txt', delimiter='::')
edges_all = edges_all.astype(int)
print(edges_all)

[[         0          0          0 1548565200]
 [         0          0          1 1548565200]
 [         1          0          2 1539144000]
 ...
 [      4843       3116       1492 1537588800]
 [      8920       3117         35 1531454400]
 [      8921       3118        235 1552194000]]


In [19]:
buyer_item = edges_all[:, 0:2]
item_seller = edges_all[:, 1:3]

In [20]:
indices = np.arange(edges_all.shape[0])
np.random.shuffle(indices)

nums = edges_all.shape[0]
num_val = int(nums * 0.15)
num_test = int(nums * 0.15)
num_train = nums - num_val - num_test

train_indices = indices[:num_train]
val_indices = indices[num_train:num_train+num_val]
test_indices = indices[num_train+num_val:]


train_set = {}
val_set = {}
test_set = {}
buyer_item_set = {}
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1
    if i in train_indices:
        train_set[pair] = 1
    elif i in val_indices:
        val_set[pair] = 1
    elif i in test_indices:
        test_set[pair] = 1
    else:
        print("Error")

buyer_item_outputs = []
train_outputs = []
val_outputs = []
test_outputs = []
for idx, (pair, count) in enumerate(buyer_item_set.items()):
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)
    if pair in train_set.keys():
        train_outputs.append(idx)
    if pair in val_set.keys():
        val_outputs.append(idx)
    if pair in test_set.keys():
        test_outputs.append(idx)
train_outputs = np.array(train_outputs, dtype=int)
val_outputs = np.array(val_outputs, dtype=int)
test_outputs = np.array(test_outputs, dtype=int)
print(train_outputs.shape)
print(val_outputs.shape)
print(test_outputs.shape)

(19016,)
(5224,)
(5200,)


In [21]:
print(train_outputs)
with open('data/split/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)
np.savetxt('data/split/buyer_item_train.txt', train_outputs, fmt='%i')
np.savetxt('data/split/buyer_item_val.txt', val_outputs, fmt='%i')
np.savetxt('data/split/buyer_item_test.txt', test_outputs, fmt='%i')

[    0     1     2 ... 24877 24879 24880]


In [22]:
train_set = {}
val_set = {}
test_set = {}
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1
    if i in train_indices:
        train_set[pair] = 1
    elif i in val_indices:
        val_set[pair] = 1
    elif i in test_indices:
        test_set[pair] = 1
    else:
        print("Error")

item_seller_outputs = []
train_outputs = []
val_outputs = []
test_outputs = []
for idx, (pair, count) in enumerate(item_seller_set.items()):
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    item_seller_outputs.append(line)
    if pair in train_set.keys():
        train_outputs.append(idx)
    if pair in val_set.keys():
        val_outputs.append(idx)
    if pair in test_set.keys():
        test_outputs.append(idx)
train_outputs = np.array(train_outputs, dtype=int)
val_outputs = np.array(val_outputs, dtype=int)
test_outputs = np.array(test_outputs, dtype=int)
print(train_outputs.shape)
print(val_outputs.shape)
print(test_outputs.shape)

(12724,)
(3725,)
(3771,)


In [23]:
print(train_outputs)
with open('data/split/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)
np.savetxt('data/split/item_seller_train.txt', train_outputs, fmt='%i')
np.savetxt('data/split/item_seller_val.txt', val_outputs, fmt='%i')
np.savetxt('data/split/item_seller_test.txt', test_outputs, fmt='%i')

[    2     3     5 ... 16628 16630 16631]


In [22]:
buyer_item_set = {}
for i in range(buyer_item.shape[0]):
    pair = buyer_item[i, 0], buyer_item[i, 1]
    if pair not in buyer_item_set.keys():
        buyer_item_set[pair] = 1
    else:
        buyer_item_set[pair] += 1

buyer_item_outputs = []
for pair, count in buyer_item_set.items():
    buyer, item = pair
    line = ' '.join([str(buyer), str(item), str(count)]) + '\n'
    buyer_item_outputs.append(line)

In [23]:
with open('data/buyer_item.txt', 'w') as fp:
	fp.writelines(buyer_item_outputs)

In [24]:
item_seller_set = {}
for i in range(item_seller.shape[0]):
    pair = item_seller[i, 0], item_seller[i, 1]
    if pair not in item_seller_set.keys():
        item_seller_set[pair] = 1
    else:
        item_seller_set[pair] += 1

item_seller_outputs = []
for pair, count in item_seller_set.items():
    item, seller = pair
    line = ' '.join([str(item), str(seller), str(count)]) + '\n'
    item_seller_outputs.append(line)

In [25]:
with open('data/item_seller.txt', 'w') as fp:
	fp.writelines(item_seller_outputs)